apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-server
  template:
    metadata:
      labels:
        app: authorization-server
    spec:
      containers:
        - name: authorization-server
          image: authorization-server:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
---
apiVersion: v1
kind: Service
metadata:
  name: authorization-server
spec:
  selector:
    app: authorization-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080