spring:
  security:
    oauth2:
      authorization-server:
        client:
          client-1:
            require-authorization-consent: true
            token:
              # set it to 3 minutes, default is 5 minutes
              access-token-time-to-live: 180s
            registration:
              client-id: gateway
              client-secret: "{noop}password"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://localhost:8082/login/oauth2/code/spring
              scopes:
                - openid
                - user.read
                - user.write

        issuer: http://authorization-server:8080

logging.level:
  org.springframework.security: DEBUG
  org.springframework.security.oauth2.server.authorization: DEBUG