apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-service
  template:
    metadata:
      labels:
        app: greeting-service
    spec:
      containers:
        - name: greeting-service
          image: greeting-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-service
spec:
  selector:
    app: greeting-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080