apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
data:
  # full configuration: https://developer.hashicorp.com/vault/docs/configuration

  # Used by the Sidecar (The Proxy)
  config.hcl: |
    vault {
      address = "http://my-vault.default.svc:8200"
    }
    # https://developer.hashicorp.com/vault/docs/agent-and-proxy/autoauth
    auto_auth {
      # the desired authentication method for the current environment
      method "approle" {
        mount_path = "auth/approle"
        config = {
          role_id_file_path = "/vault/custom/role-id"
          secret_id_file_path = "/vault/custom/secret-id"
        }
      }
      # the location where tools save tokens when the token value changes
      sink "file" {
        config = {
          path = "/home/vault/.vault-token"
        }
        type = "file"
      }
    }
      
    # deprecated - https://developer.hashicorp.com/vault/docs/agent-and-proxy/agent/apiproxy
    api_proxy {
      use_auto_auth_token = "force"
    }
  
    listener "tcp" {
      address     = "127.0.0.1:8200"
      tls_disable = true      
    }
    exit_after_auth = false

  # Used by the Init Container (The Setup)
  config-init.hcl: |
    vault {
      address = "http://my-vault.default.svc:8200"
    }
    
    auto_auth {
      method "approle" {
        mount_path = "auth/approle"
        config = {
          role_id_file_path = "/vault/custom/role-id"
          secret_id_file_path = "/vault/custom/secret-id"
        }
      }
      sink "file" {
        config = {
          path = "/home/vault/.vault-token"
        }
      }
    }
    exit_after_auth = true
